/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cardart;


import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;


import javax.swing.JOptionPane;


/**
 *
 * @author SINUTECH
 */
public class AgregarUI extends javax.swing.JPanel {

    
    
    /**
     * Creates new form AgregarUI
     */
    public AgregarUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TextAgg = new javax.swing.JTextArea();
        BoxCatAgg = new javax.swing.JComboBox<>();
        Btn_agg = new javax.swing.JButton();
        Btn_AggImg = new javax.swing.JButton();
        Btn_Imp = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 121, 107));
        setMaximumSize(new java.awt.Dimension(560, 300));
        setMinimumSize(new java.awt.Dimension(560, 300));

        TextAgg.setColumns(20);
        TextAgg.setLineWrap(true);
        TextAgg.setRows(5);
        TextAgg.setBorder(null);
        jScrollPane1.setViewportView(TextAgg);

        BoxCatAgg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BoxCatAgg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agradecimientos", "Amistad", "Amor", "Aniversario", "Comuniones", "Condolencias", "Cumpleaños", "Grados", "Matrimonios", "Navidad", "Quince_Años", "Reconciliacion" }));
        BoxCatAgg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxCatAggActionPerformed(evt);
            }
        });

        Btn_agg.setBackground(new java.awt.Color(2, 119, 189));
        Btn_agg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Btn_agg.setForeground(new java.awt.Color(255, 255, 255));
        Btn_agg.setText("Agregar");
        Btn_agg.setBorder(null);
        Btn_agg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_aggActionPerformed(evt);
            }
        });

        Btn_AggImg.setBackground(new java.awt.Color(0, 230, 118));
        Btn_AggImg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Btn_AggImg.setForeground(new java.awt.Color(255, 255, 255));
        Btn_AggImg.setText("Pre-Diseño");
        Btn_AggImg.setBorder(null);
        Btn_AggImg.setMaximumSize(new java.awt.Dimension(57, 17));
        Btn_AggImg.setMinimumSize(new java.awt.Dimension(57, 17));
        Btn_AggImg.setPreferredSize(new java.awt.Dimension(57, 17));

        Btn_Imp.setBackground(new java.awt.Color(0, 230, 118));
        Btn_Imp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Btn_Imp.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Imp.setText("Imprimir");
        Btn_Imp.setBorder(null);
        Btn_Imp.setMaximumSize(new java.awt.Dimension(57, 17));
        Btn_Imp.setMinimumSize(new java.awt.Dimension(57, 17));
        Btn_Imp.setPreferredSize(new java.awt.Dimension(57, 17));
        Btn_Imp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ImpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BoxCatAgg, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btn_agg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btn_AggImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btn_Imp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BoxCatAgg, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Btn_agg, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Btn_Imp, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Btn_AggImg, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(95, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_aggActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_aggActionPerformed
        Conectar cc = new Conectar();
        Connection cn = cc.conexion();
        cc.conexion();
        String text, cat, sql;
        text = TextAgg.getText();
        cat = BoxCatAgg.getSelectedItem().toString().toLowerCase();
        
//        sql = "INSERT INTO "+cat+" (text_me) VALUES (?)";
        try {
            PreparedStatement pst = cn.prepareStatement("INSERT INTO "+cat+" (tex_me) VALUES (?)");
            pst.setString(1, text);
            int n= pst.executeUpdate();
            if (n>0){
                JOptionPane.showMessageDialog(null, "Guardado Con Exito");
            }
        } catch (SQLException ex) {
            Logger.getLogger(AgregarUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        TextAgg.setText("");
        
        
        
        
    }//GEN-LAST:event_Btn_aggActionPerformed

     private void TextAggActionPerformed(java.awt.event.ActionEvent evt) {                                          
      TextAgg.transferFocus();
    }  
    private void Btn_ImpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ImpActionPerformed
Imprimir nn = new Imprimir();
Imprimir.TextAgg2.setText(TextAgg.getText());
               nn.setLocationRelativeTo(null);
               nn.setVisible(true);
        
    }//GEN-LAST:event_Btn_ImpActionPerformed

    private void BoxCatAggActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxCatAggActionPerformed
      BoxCatAgg.transferFocus();
    }//GEN-LAST:event_BoxCatAggActionPerformed
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BoxCatAgg;
    private javax.swing.JButton Btn_AggImg;
    private javax.swing.JButton Btn_Imp;
    private javax.swing.JButton Btn_agg;
    public static javax.swing.JTextArea TextAgg;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
