/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabajobanco;

import javax.swing.JOptionPane;

/**
 *
 * @author manue
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("THE WORLD BANK");

        jButton1.setText("Insetar Datos del Banco");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Ver Datos del Banco");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Registrar un Cliente");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Eliminar un Cliente");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Realizar Consignaion");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Realizar Retiro");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Cosultar Saldo");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Consultar Movimiento");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Salir");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(118, 118, 118))
            .addGroup(layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jButton9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addGap(18, 18, 18)
                .addComponent(jButton9)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Banco obj=new Banco();
    int pos=0;
    Cuenta cuent;
    Clientes client;
    Movimiento mov;
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        obj.setGerente(JOptionPane.showInputDialog("Ingrese el nombre del gerente"));
        obj.setTelefono(JOptionPane.showInputDialog("Ingrese el numero de telefono"));
        obj.setCorreo(JOptionPane.showInputDialog("Ingrese el correo"));
        obj.setDireccion(JOptionPane.showInputDialog("Ingrese la direccion"));
        obj.setNelementos(Integer.parseInt(JOptionPane.showInputDialog("Ingrese el numero de clientes")));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String datos="Gerente: "+obj.getGerente()+"\n"
                + "Telefono: "+obj.getTelefono()+"\n"
                + "Correo: "+obj.getCorreo()+"\n"
                + "Direccion: "+obj.getDireccion()+"\n";
        JOptionPane.showMessageDialog(rootPane, datos, "Datos del Banco", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (pos < obj.getNelementos()) {
            client = new Clientes();
            cuent=new Cuenta();
            client.setNombre(JOptionPane.showInputDialog("Ingrese el nombre del cliente"));
            client.setIdcliente(Integer.parseInt(JOptionPane.showInputDialog("Ingrese el id del cliente")));
            client.setCorreo(JOptionPane.showInputDialog("Ingrese el correo del cliente"));
            client.setDireccion(JOptionPane.showInputDialog("Ingrese la direccion del cliente"));
            client.setTelefono(JOptionPane.showInputDialog("ingrese el telefono del cliente"));
            
            cuent.setDatoscliente(client);
            cuent.setTipocuenta(JOptionPane.showInputDialog("ingrese el tipo de cuenta"));
            cuent.setNumcuenta(Integer.parseInt(JOptionPane.showInputDialog("Ingrese el numero de cuenta")));
            cuent.setSaldo(Float.parseFloat(JOptionPane.showInputDialog("Ingrese el saldo inicial")));
            cuent.setNmovimiento(Integer.parseInt(JOptionPane.showInputDialog("Ingrese el maximo numero de movimientos permitidos")));
            
            obj.insertarcuenta(pos, cuent);
            pos++;
        }else{
            JOptionPane.showMessageDialog(rootPane, "Se alcanzo el maximo numero de clientes permitidos");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int parametro=Integer.parseInt(JOptionPane.showInputDialog("Ingrese el id del cliente a eliminar"));
        int res=obj.busqueda(parametro);
        if (res!=-1) {
            obj.eliminar(pos);
            JOptionPane.showMessageDialog(rootPane, "La cuenta ha sido eliminada");
        }else{
            JOptionPane.showMessageDialog(rootPane, "La cuenta no se encuentra registrada");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int parametro=Integer.parseInt(JOptionPane.showInputDialog("Ingrese el id del cliente al que desea consignar"));
        int res=obj.busqueda(parametro);
        if (res!=-1 && obj.getListaCuenta(res).getPosicionactual()<obj.getListaCuenta(res).getNmovimiento()) {
            mov=new Movimiento();
            float saldo=Float.parseFloat(JOptionPane.showInputDialog("Ingrese la cantidad a consignar"));
            mov.setFecha(JOptionPane.showInputDialog("Ingrese la fecha"));
            mov.setIdmoviento(Integer.parseInt(JOptionPane.showInputDialog("Ingrese el id del movimiento")));
            mov.setTipo("Consigancion");
            mov.setQuienRealiza(JOptionPane.showInputDialog("Ingrese el nombre de quien realiza"));
            mov.setValor(saldo);
            
            obj.getListaCuenta(res).Consignar(saldo, mov);
            
        }else{
            JOptionPane.showMessageDialog(rootPane, "La cuenta no se encuentra registrada");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int parametro=Integer.parseInt(JOptionPane.showInputDialog("Ingrese el id del cliente al que desea retirar"));
        int res=obj.busqueda(parametro);
        if (res!=-1 && obj.getListaCuenta(res).getPosicionactual()<obj.getListaCuenta(res).getNmovimiento()) {
            mov=new Movimiento();
            float saldo=Float.parseFloat(JOptionPane.showInputDialog("Ingrese la cantidad a retirar"));
            mov.setFecha(JOptionPane.showInputDialog("Ingrese la fecha"));
            mov.setIdmoviento(Integer.parseInt(JOptionPane.showInputDialog("Ingrese el id del movimiento")));
            mov.setTipo("Retiro");
            mov.setQuienRealiza(JOptionPane.showInputDialog("Ingrese el nombre de quien realiza"));
            mov.setValor(saldo);
            
            obj.getListaCuenta(res).Retiro(saldo, mov);
            
        }else{
            JOptionPane.showMessageDialog(rootPane, "La cuenta no se encuentra registrada");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        int parametro=Integer.parseInt(JOptionPane.showInputDialog("Ingrese el id del cliente a consultar"));
        int res=obj.busqueda(parametro);
        if (res!=-1) {
            JOptionPane.showMessageDialog(rootPane, "el saldo de la cuenta es: "+obj.getListaCuenta(res).getSaldo());
        }else{
            JOptionPane.showMessageDialog(rootPane, "La cuenta no se encuentra registrada");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        int parametro=Integer.parseInt(JOptionPane.showInputDialog("Ingrese el id del cliente a consultar"));
        int res=obj.busqueda(parametro);
        if (res!=-1){
            int id=Integer.parseInt(JOptionPane.showInputDialog("Ingrese el id del movimiento a consultar"));
            Movimiento result=obj.consultarmovimiento(pos, id);
            if (result!=null) {
                JOptionPane.showMessageDialog(rootPane, "ID del movimiento: " + result.getIdmoviento() + "\n"
                        + "Fecha: " + result.getFecha() + "\n"
                        + "Tipo: " + result.getTipo() + "\n"
                        + "Nombre de quien realizo: " + result.getQuienRealiza() + "\n"
                        + "Valor: " + result.getValor() + "\n");
            }else{
                JOptionPane.showMessageDialog(rootPane, "No encontro el movimientro ingresado");
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "La cuenta no se encuentra registrada");
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
